require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

AllCops:
  NewCops: enable
  